
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN NUMBER RPAREN SYMBOLexpression : LPAREN explist RPAREN\n                   explist : expression\n                | explist expression\n    expression : NUMBERexpression : SYMBOL'
    
_lr_action_items = {'NUMBER':([0,2,3,4,5,6,7,8,],[3,3,-4,-5,-2,3,-3,-1,]),'RPAREN':([3,4,5,6,7,8,],[-4,-5,-2,8,-3,-1,]),'$end':([1,3,4,8,],[0,-4,-5,-1,]),'LPAREN':([0,2,3,4,5,6,7,8,],[2,2,-4,-5,-2,2,-3,-1,]),'SYMBOL':([0,2,3,4,5,6,7,8,],[4,4,-4,-5,-2,4,-3,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,6,],[1,5,7,]),'explist':([2,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN explist RPAREN','expression',3,'p_expr','parser.py',67),
  ('explist -> expression','explist',1,'p_expr_list','parser.py',76),
  ('explist -> explist expression','explist',2,'p_expr_list','parser.py',77),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',86),
  ('expression -> SYMBOL','expression',1,'p_expression_symbol','parser.py',90),
]
